app:
    resource: "@AppBundle/Controller/"
    type:     annotation

recipes:
    path: "recipes/{slug}"
    defaults: { _controller: AppBundle:Recipes:index, slug: no-name }
    requirements:
        slug:   "[a-z\-]+"
    
#recipes:
#    path: "recipes/{id}"
#    defaults: { _controller: AppBundle:Recipes:index }