app:
    resource: "@AppBundle/Controller/"
    type:     annotation

recipes:
    path: "recipes/{id}"
    defaults: { _controller: AppBundle:Recipes:index }
    
#recipes:
#    path: "recipes/{id}"
#    defaults: { _controller: AppBundle:Recipes:index }